### ISSUE TITLE
Are you serious?

### ISSUE THREAD

**Issue by tripulse** [HO-COOH/CPPDevOnWindows#1]
Windows was never intended to be hacker friendly, thus the ecosystem formed in a way to match average consumer skillset. Consumers do not care about aspects like package managing or [file hierarchy standards](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html), which makes the life of a Windows hacker just hell, it has been an issue for long.

Consumers assume using computers has to be painful so they remain silent about it but they're not aware that it is avoidable using a sane system, which Windows clearly isn't. The Windows hacker community has realised this, but it's real hard to move off the comfort zone.

So recently, what the community has been doing is laughable. They are trying to do so-called "improvement" of the situation by adding package managers which are just a tiny subset of what we have in the UNIX realm. A package manager should be an integral part of a system but you still have to install drivers off the vendors website, whereas we can do that by running some simple command(s).

The people of the UNIX realm were busy in doing these things and Microsoft in [EEE](https://en.wikipedia.org/wiki/Embrace,_extend,_and_extinguish)ing companies. It's not that Microsoft didn't make standards, [they made](https://en.wikipedia.org/wiki/Office_Open_XML) but they were [utterly useless](https://en.wikipedia.org/wiki/Standardization_of_Office_Open_XML).

Since there's no file hierarchy standard you can't know what resides where, thus no notion of shared dependencies. While the OS has support for DLLs, it is effectively the same as static linking because the DLLs are isolated into a single program. This situation isn't going to improve because the actions were not taken in the past, now it grew past to the point where it is impossible to do so and Microsoft isn't worried about this because they know that it isn't going to harm their market share.

---

> I know a lot of you are having troubles of getting it to work on Windows and complaining a shiton.

This statement exactly supports my point LOL.

> You can just use Visual Studio, which is the best and beginner-friendly solution, but for some reason you are just a boomer and don't want to use it.

> which is the best

From what angle? Oh you mean best at crashing randomly and collecting telemetry? Sure.

> beginner-friendly

Yes. Making the *beginners'* always depend on Visual Studio in future and confine himself in the Windows miasma.

> I can understand you don't want to use Visual Studio because it's slow or for whatever reason. But you HAVE TO install Visual Studio on Windows to use vcpkg. (Mingw GCC CAN NOT be used to build vcpkg on Windows at the time being)

> But you HAVE TO install Visual Studio on Windows to use vcpkg.

MSYS2 has a [package manager](https://www.msys2.org/docs/package-management/) already which is far more versatile than vcpkg. Where as vcpkg downloads the source code off the internet then compiles them, which is a waste of time. vcpkg is leaned towards CMake and Visual Studio and it doesn't care about other buildsystems at all (eg. meson), as if they don't exist.

What is so good about vcpkg that I "HAVE TO" use it? You can always `./configure && make && make install` which is not buildsystem specific and allows you to configure the compilation to your own needs.

> MSVC being a Microsoft C/C++ compiler is a legit and good compiler

The Microsoft compiler repeatedly tries to push users into following non-standard ways, [such as using `scanf_s` over `scanf`](https://stackoverflow.com/questions/372980/do-you-use-the-tr-24731-safe-functions). The problem is that it can issue a warning but it issues an error instead and requires to define `_CRT_SECURE_NO_WARNINGS` to suppress it. I have seen no compiler that does this.

Also, since we cannot view the source code of the compiler due to it's proprietary, it's hard to tell that it *is* designed good. Clang and GCC are really good compilers and both have source code viewable.

**Comment by HO-COOH** [comment]
Windows is "kind of" harder to setup for C/C++ development than Linux and that's exactly the reason I am writing this tutorial for. What are you even trying to argue? 
What's wrong for beginner to depend on Visual Studio? What's that any different to beginner to depend on GCC/Clang/Xcode with clang? Non beginner can trivially switch to other compilers & toolchains. I am writing a new part about installing MSVC as a standalone compiler, which does not require a visual studio installation. And also, visual studio can be installed as a standalone C++ ide, without the MSVC compiler :)

CMake solves everything wrong about `make`. And I don't even bother to mention them.
> You can always ./configure && make && make install which is not buildsystem specific
Sorry but `make` is one build system that cmake can target to, called `GNU Makefiles`.

After all, issues is for "issues". Being constructive means you have some better ways of setting up C/C++ development **on Windows** and get better experience.

**Comment by tripulse** [comment]
> What's wrong for beginner to depend on Visual Studio?

I believe they wouldn't be able to switch to environments where Visual Studio isn't available (eg. GNU/Linux).

> CMake solves everything wrong about `make`. And I don't even bother to mention them.

Nothing is *wrong* about make, it does what it's destined to it is close to shell scripting with some additional features. That is why `./configure` exists for generating Makefiles. CMake claims to do the job of `./configure` but it can't create freestanding Makefiles like `./configure`, the Makefile calls back to the CMake binary. I'd say, it adds more problems than fixing them.

> After all, issues is for "issues". Being constructive means you have some better ways of setting up C/C++ development on Windows and get better experience.

Just keep this guide to the MSYS2 and GCC part and maybe the CMake part if you wish, it is the only relevant part.

About package managers, *Chocolatey* and *Winget* maybe "easy-to-use" but they're not a total solution, for example I find no development packages or driver packages or less known utility packages.

**Comment by HO-COOH** [comment]
I am a beginner started from "depending" on Visual Studio 2013 and I think I am an example that able to still code without it. :)

Talk is cheap. Show me your way of installing a C/C++ library using whatever package manager **on Windows** you think is the easiest (`boost` is your best bet I guess), and achieve the minimum of the following things:
1. Get auto-complete of that library with whatever your editor/IDE
2. Write a simple program using that library
3. Build it, with both Debug and Release mode, with whatever build system you like

As a comparison, my way of using `vcpkg` and `cmake` with visual studio code, setting the toolchain fie is a one-time setting. Essentially all you need to do is one line to install a library line in `vcpkg` and then copy the `target_link_libraires()` that `vcpkg` provided to you in your `CMakeLists.txt`, and vscode's extension auto configures everything.

**Comment by HO-COOH** [comment]
#f6a8b3d
Added everything you want.
