### ISSUE TITLE
Why does Msys2 install python 3.9?

### ISSUE THREAD

**Issue by jamiecropley** [HO-COOH/CPPDevOnWindows#4]
C:\msys64\mingw64\bin in this directory it installs Python 3.9 under file python3.9.exe msys2 install environment variable at system level where python windows installed sets the path at user level.

To fix I simply copied the path from the user environment variables for python 3.10 I have installed into the system variables and put above msys2/msys64 as per the below screenshot

![image](https://user-images.githubusercontent.com/17186004/166696112-74fd4cd3-e17d-47c9-b809-cbe2a1b2814f.png)

This seems to have fixed it.

But I am worried because...

1. Why is Msys2 installing Python 3.9 in the first place? I don't recall this being part of your tutorial and what need would it have for c/c++ kind of dynamic?
2. The way I have now set this up with Python 3.10 overriding system default of 3.9 (installed via msys) will this effect anything like pacman, vcpkg, c and c++ compilers etc... going forward?

**Comment by HO-COOH** [comment]
I think it's required by `gdb`.
```
$ pacman -R mingw-w64-x86_64-python
checking dependencies...
error: failed to prepare transaction (could not satisfy dependencies)
:: removing mingw-w64-x86_64-python breaks dependency 'mingw-w64-x86_64-python' required by mingw-w64-x86_64-gdb
:: removing mingw-w64-x86_64-python breaks dependency 'mingw-w64-x86_64-python' required by mingw-w64-x86_64-glib2
```
