### ISSUE TITLE
screenshot lose

### ISSUE THREAD

**Issue by lcy19** [HO-COOH/CPPDevOnWindows#6]
Thanks for your work. the `screenshots/Editor/VSCode/Extension_Cmake_Setting.png` was lost, please add it sometime, thx again~

**Comment by soulimane-mammar** [comment]
Some screenshots are missing. Great work

**Comment by HO-COOH** [comment]
I added them and in the mean time I rewalked through it and found quite some pieces have been changed and have been made easier than the time I wrote this guide, but the steps still applies. I might need to find time to rewrite them, but let's call it a day for now :)
